<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

		/* application/controllers/Groupss.php */
    /* MPAMPAM CRUD GENERATOR */
    /* PENGEMBANG : MPAMPAM */
    /* EMAIL : MPAMPAM5@GMAIL.COM */
    /* FACEBOOK : https://www.facebook.com/mpampam */
    /* Generated by MPAMPAM CRUD GENERTOR 2019-05-14 03:51:43 */
    /* https://mpampam.com */